### ISSUE TITLE
Running RTSPtoWeb Outside of Config Directory

### ISSUE THREAD

**Issue by dbq-andersons** [deepch/RTSPtoWeb#122]
When I pull down and build RTSPtoWeb, I find that I need to be in the config directory to run it.

Running it from within the config directory works fine:

```
anderson@steve:/tools/go/RTSPtoWeb$ pwd
/tools/go/RTSPtoWeb
anderson@steve:/tools/go/RTSPtoWeb$ /tools/go/RTSPtoWeb/RTSPtoWeb -config /tools/go/RTSPtoWeb/config.json
INFO[2022-03-11T11:45:40-06:00] Server CORE start                             func=main module=main
INFO[2022-03-11T11:45:40-06:00] Run stream                                    call=Run channel=0 func=StreamServerRunStreamDo module=core stream=9185732c-682a-411d-b29d-eec2e99ad280
INFO[2022-03-11T11:45:40-06:00] Server HTTP start                             call=Start func=RTSPServer module=http_server
INFO[2022-03-11T11:45:40-06:00] Server start success a wait signals           func=main module=main
INFO[2022-03-11T11:45:40-06:00] Server RTSP start                             call=Start func=RTSPServer module=rtsp_server
INFO[2022-03-11T11:45:40-06:00] Run stream                                    call=Run channel=0 func=StreamServerRunStreamDo module=core stream=e7094244-1b53-457a-b392-5c4c9421a51f
INFO[2022-03-11T11:45:40-06:00] Success connection RTSP                       call=Start channel=0 func=StreamServerRunStream module=core stream=9185732c-682a-411d-b29d-eec2e99ad280
INFO[2022-03-11T11:45:40-06:00] Success connection RTSP                       call=Start channel=0 func=StreamServerRunStream module=core stream=e7094244-1b53-457a-b392-5c4c9421a51f
^CINFO[2022-03-11T11:45:47-06:00] Server receive signalinterrupt                func=main module=main
INFO[2022-03-11T11:45:47-06:00] Stream exit by signal or not client           call=StreamServerRunStream channel=0 func=StreamServerRunStreamDo module=core stream=e7094244-1b53-457a-b392-5c4c9421a51f
INFO[2022-03-11T11:45:47-06:00] Stream exit by signal or not client           call=StreamServerRunStream channel=0 func=StreamServerRunStreamDo module=core stream=9185732c-682a-411d-b29d-eec2e99ad280
INFO[2022-03-11T11:45:49-06:00] Server stop working by signal                 func=main module=main
anderson@steve:/tools/go/RTSPtoWeb$
```

However, if I try to run it from anywhere else on the system (say to configure to auto-start on boot or something), it can't find the web/templates directory (and possibly other stuff since that's all the farther it gets).

```
anderson@steve:~$ pwd
/home/anderson
anderson@steve:~$ /tools/go/RTSPtoWeb/RTSPtoWeb -config /tools/go/RTSPtoWeb/config.json
INFO[2022-03-11T11:45:58-06:00] Server CORE start                             func=main module=main
INFO[2022-03-11T11:45:58-06:00] Server HTTP start                             call=Start func=RTSPServer module=http_server
INFO[2022-03-11T11:45:58-06:00] Server RTSP start                             call=Start func=RTSPServer module=rtsp_server
panic: html/template: pattern matches no files: `web/templates/*`

goroutine 7 [running]:
html/template.Must(...)
        /snap/go/9028/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0004a4000, {0xc00048c070, 0xf})
        /home/anderson/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:225 +0x2db
main.HTTPAPIServer()
        /tools/go/RTSPtoWeb/apiHTTPRouter.go:43 +0x515
created by main.main
        /tools/go/RTSPtoWeb/RTSPtoWeb.go:17 +0x188
anderson@steve:~$
```

Is this a thing I can do?  If so, what am I missing?

Thanks,

Bill

**Comment by allenporter** [comment]
See the `http_dir` option in `config.json`

**Comment by allenporter** [comment]
Here is an example: https://github.com/allenporter/stream-addons/blob/9d33dbfdc5504afc40ea0ffdfa3d13e106a22da5/rtsp-to-web/rootfs/app/config.json#L6
