### ISSUE TITLE
can't play some rtsp

### ISSUE THREAD

**Issue by Hyalei** [deepch/RTSPtoWeb#213]
![83ee1ee63df6a8f020096d92039054e](https://user-images.githubusercontent.com/91814111/188426715-e02aa0a9-e131-4f6e-93d0-99a2bca37159.jpg)
![3b03192a0bf65147ec91ee61bbdff59](https://user-images.githubusercontent.com/91814111/188426732-5ed6b7c2-2095-449c-a36b-5cbeca263601.jpg)

When I tried to convert this RTSP, the program repeatedly reported an error.
I can provide my RTSP for you to test at any time

**Comment by deepch** [comment]
incorect camera stream url

**Comment by Hyalei** [comment]
> incorect camera stream url

But I can play it with VLC player

**Comment by Hyalei** [comment]
```
2022/09/06 10:45:42 [RTSP/1.0 200 OK
CSeq: 2
Server: MgcServer
Content-Type: application/sdp
Content-Base: rtsp://123.6.110.87:554/openUrl/gxHMokU
Content-Length: 772

v=0
o=- 1000617 1000617 IN IP4 0.0.0.0
s=hikvision
c=IN IP4 0.0.0.0
a=range:npt=now-
a=control:rtsp://123.6.110.87:554/openUrl/gxHMokU
t=0 0
a=ezsdkkey:-
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=8;config=Z0KAH4iLQCgC3QgAADhAAAr8gCA=,aM44gA==
a=control:rtsp://123.6.110.87:554/openUrl/gxHMokU/trackID=0
a=range:npt=now-
m=audio 0 RTP/AVP 104
c=IN IP4 0.0.0.0
a=rtpmap:104 MPEG4-GENERIC/16000
a=fmtp:104 streamtype=5;profile-level-id=15;mode=AAC-hbr;config=1408;SizeLength=13;IndexLength=3;IndexDeltaLength=3;Profile=1;
a=control:rtsp://123.6.110.87:554/openUrl/gxHMokU/trackID=1
a=range:npt=now-
a=Media_header:MEDIAINFO=494D4B48030100000400000101200110803E0000007D000000000000000000000000000000000000;

]
2022/09/06 10:45:42 [SETUP rtsp://123.6.110.87:554/openUrl/gxHMokU/trackID=0 RTSP/1.0
CSeq: 3
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
User-Agent: Lavf58.76.100

]
2022/09/06 10:45:42 [RTSP/1.0 200 OK
CSeq: 3
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Session: 1000617;timeout=8
Server: MgcServer

]
2022/09/06 10:45:42 [PLAY rtsp://123.6.110.87:554/openUrl/gxHMokU RTSP/1.0
CSeq: 4
User-Agent: Lavf58.76.100
Session: 1000617

]
time="2022-09-06T10:45:43+08:00" level=error msg="Stream error restart stream Camera send statusRTSP/1.0 500 Internal Server Error" call=Restart
2022/09/06 10:45:43 http: panic serving 127.0.0.1:4618: runtime error: invalid memory address or nil pointer dereference
goroutine 3782 [running]:
net/http.(*conn).serve.func1()
        C:/Users/HYL/sdk/go1.18/src/net/http/server.go:1825 +0xbf
panic({0x919ba0, 0xf91110})
        C:/Users/HYL/sdk/go1.18/src/runtime/panic.go:844 +0x258
main.(*MuxerHLS).GetIndexM3u8(0x0, 0xffffffffffffffff, 0xffffffffffffffff)
        D:/GoCode/RTSPtoWeb-master/hlsMuxer.go:158 +0x27
main.(*StorageST).HLSMuxerM3U8(0xc000448000, {0xc0004c200c, 0x24}, {0xc0004c2039, 0x1}, 0x1b4627?, 0x215ec0?)
        D:/GoCode/RTSPtoWeb-master/storageStreamChannel.go:400 +0x1b6
main.HTTPAPIServerStreamHLSLLM3U8(0xc000540900)
        D:/GoCode/RTSPtoWeb-master/apiHTTPHLSLL.go:83 +0x665
github.com/gin-gonic/gin.(*Context).Next(...)
        D:/GoCode/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
main.CrossOrigin.func1(0xc000540900)
        D:/GoCode/RTSPtoWeb-master/apiHTTPRouter.go:296 +0x2f9
github.com/gin-gonic/gin.(*Context).Next(...)
        D:/GoCode/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00040e680, 0xc000540900)
        D:/GoCode/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00040e680, {0xb28278?, 0xc0002c42a0}, 0xc000540000)
        D:/GoCode/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 +0x1dd
net/http.serverHandler.ServeHTTP({0xc000eaa420?}, {0xb28278, 0xc0002c42a0}, 0xc000540000)
        C:/Users/HYL/sdk/go1.18/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001ba3c0, {0xb28a68, 0xc0000f5710})
        C:/Users/HYL/sdk/go1.18/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        C:/Users/HYL/sdk/go1.18/src/net/http/server.go:3071 +0x4db
time="2022-09-06T10:45:45+08:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=d219d581-d1f4-4308-a96e-591d885afc7c
2022/09/06 10:45:45 [OPTIONS rtsp://123.6.110.87:554/openUrl/gxHMokU RTSP/1.0
CSeq: 1
User-Agent: Lavf58.76.100

]
2022/09/06 10:45:45 [RTSP/1.0 200 OK
CSeq: 1
Server: MgcServer
Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, HEARTBEAT, GET_PARAMETER, SET_PARAMETER
SupportAuth: AES BASE64

]
2022/09/06 10:45:45 [DESCRIBE rtsp://123.6.110.87:554/openUrl/gxHMokU RTSP/1.0
CSeq: 2
Accept: application/sdp
User-Agent: Lavf58.76.100

]
```
The above is the program log that I found and printed in debug mode. The program can get SDP information at the beginning, but then throws " "
In addition, when I initially used the vlc player to play my rtsp stream, it couldn't play normally, because it would be stuck in a picture and not move. When I adjusted the Live555 stream transport option to RTP over RTSP, the picture could be is played normally, do I need to set something else besides asking for h264?
![image](https://user-images.githubusercontent.com/91814111/188568844-00455639-7dce-4b4d-871c-e424e560fc4b.png)

**Comment by Nisthar** [comment]
@Hyalei why did you close this issue? did you fix it?

**Comment by Nisthar** [comment]
@Hyalei why did you close this issue? did you fix it?
