### ISSUE TITLE
Docker Container with RTSPtoWeb Crashing constantly..

### ISSUE THREAD

**Issue by mrdmiller2** [deepch/RTSPtoWeb#220]
I have about 15 cameras (defined from Frigate) and basically after getting 4 cameras in (which DO render and work)… I’m getting a hard crash of the docker container. Even after removing the cameras, and trying to restart the container, it starts up and dies right away with panic. This panic (the one below) is just with a single camera added.  If I reboot the entire server, it works for a while but will crash eventually with this log.

[s6-init] making user provided files available at /var/run/s6/etc…exited 0.
[s6-init] ensuring user provided files have correct perms…exited 0.
[fix-attrs.d] applying ownership & permissions fixes…
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts…
[cont-init.d] 01-rtsp-to-web: executing…
[10:10:15] INFO: Updating configuration
[cont-init.d] 01-rtsp-to-web: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:10:16] INFO: Starting discovery service
[10:10:16] INFO: Starting RSTPtoWeb
[10:10:17] INFO: Successfully send discovery information to Home Assistant (8083).
panic: runtime error: index out of range [0] with length 0
goroutine 11 [running]:
main.StreamServerRunStreamRTMP(0xc000039540, 0xf, 0x12dd5e0, 0x1, 0xc0004969a0, 0x0, 0x0, 0x0)
/workspace/streamCore.go:265 +0x1291
main.StreamServerRunStream(0xc000039540, 0xf, 0x12dd5e0, 0x1, 0xc0004969a0, 0x0, 0x0, 0x0)
/workspace/streamCore.go:67 +0x14cb
main.StreamServerRunStreamDo(0xc000039540, 0xf, 0x12dd5e0, 0x1)
/workspace/streamCore.go:47 +0x4fa
created by main.(*StorageST).StreamChannelRunAll
/workspace/storageStreamChannel.go:42 +0x18a
[cont-finish.d] executing container finish scripts…
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

Each Camera looks like this in Home Assistant (obviously the camera names will all change):

type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: auto
    title: Doorbell
    webrtc_card: {}
live:
  webrtc_card:
    ui: true
  preload: false
view:
  default: live
  camera_select: live
menu:
  buttons:
    image: true
    frigate: false
    snapshots: true
  mode: overlay-top
dimensions:
  aspect_ratio_mode: dynamic
image:
  mode: camera
event_viewer:
  controls:
    next_previous:
      style: thumbnails
    thumbnails:
      mode: none
event_gallery:
  min_columns: 1

The live stream resolution for each camera is pretty much 2560x1400 (some are a little more, some a little less, but that's the average)

**Comment by mrdmiller2** [comment]
Attached is the full debug log..  As you can see, it starts up, and then dies right away..

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-rtsp-to-web: executing... 
[23:07:11] INFO: Updating configuration
[cont-init.d] 01-rtsp-to-web: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:07:12] INFO: Starting discovery service
[23:07:12] INFO: Starting RSTPtoWeb
time="2022-09-27T23:07:12-07:00" level=info msg="Server CORE start" func=main module=main
time="2022-09-27T23:07:12-07:00" level=info msg="Server HTTP start" call=Start func=RTSPServer module=http_server
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.backyard_left
time="2022-09-27T23:07:12-07:00" level=info msg="Server RTSP start" call=Start func=RTSPServer module=rtsp_server
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.ds_front_center
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.left_side_house_gate
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.right_side_house
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.backyard_right
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.livingroom
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.front_door
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.ds_front_right
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.doorbell
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.ds_front_left
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.kitchen
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.garage_cam01
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.sunroom
time="2022-09-27T23:07:12-07:00" level=info msg="Server start success a wait signals" func=main module=main
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.main_room
time="2022-09-27T23:07:12-07:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.left_side_house
[23:07:12] INFO: Successfully send discovery information to Home Assistant (8083).
time="2022-09-27T23:07:12-07:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.ds_front_center
time="2022-09-27T23:07:12-07:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.ds_front_left
time="2022-09-27T23:07:13-07:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.ds_front_right
time="2022-09-27T23:07:13-07:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.left_side_house
time="2022-09-27T23:07:13-07:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.sunroom
panic: runtime error: index out of range [0] with length 0
goroutine 27 [running]:
main.StreamServerRunStreamRTMP(0xc000296948, 0x15, 0x12dd5e0, 0x1, 0xc0004d1d90, 0x0, 0x0, 0x0)
	/workspace/streamCore.go:265 +0x1291
main.StreamServerRunStream(0xc000296948, 0x15, 0x12dd5e0, 0x1, 0xc0004d1d90, 0x0, 0x0, 0x0)
	/workspace/streamCore.go:67 +0x14cb
main.StreamServerRunStreamDo(0xc000296948, 0x15, 0x12dd5e0, 0x1)
	/workspace/streamCore.go:47 +0x4fa
created by main.(*StorageST).StreamChannelRunAll
	/workspace/storageStreamChannel.go:42 +0x18a
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
