### ISSUE TITLE
RTSPTOWEB crashing due to "Segmentation violation" ?

### ISSUE THREAD

**Issue by seededplyr** [deepch/RTSPtoWeb#256]
Any idea how I can fix this?

```
Dec 04 17:47:17 archangel rtsptoweb[317494]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 17:47:17 archangel rtsptoweb[317494]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 17:47:17 archangel rtsptoweb[317494]: goroutine 29 [running]:
Dec 04 17:47:17 archangel rtsptoweb[317494]: main.(*StorageST).StreamChannelCastProxy(0xc0002be5a0, {0xc0003390e0, 0x24}, {0x11dfd28, 0x1}, 0xc0022f0000)
Dec 04 17:47:17 archangel rtsptoweb[317494]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 17:47:17 archangel rtsptoweb[317494]: main.StreamServerRunStream({0xc0003390e0, 0x24}, {0x11dfd28, 0x1}, 0xc0003d0d10)
Dec 04 17:47:17 archangel rtsptoweb[317494]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 17:47:17 archangel rtsptoweb[317494]: main.StreamServerRunStreamDo({0xc0003390e0, 0x24}, {0x11dfd28, 0x1})
Dec 04 17:47:17 archangel rtsptoweb[317494]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 17:47:17 archangel rtsptoweb[317494]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 17:47:17 archangel rtsptoweb[317494]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 17:47:17 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 17:47:17 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 17:47:17 archangel systemd[1]: rtsptoweb.service: Consumed 13min 53.782s CPU time.
Dec 04 17:47:27 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 251.
Dec 04 17:47:47 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 17:47:47 archangel systemd[1]: rtsptoweb.service: Consumed 13min 53.782s CPU time.
Dec 04 17:47:47 archangel systemd[1]: Started RTSPtoWeb server.

Dec 04 19:18:00 archangel rtsptoweb[316]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 19:18:00 archangel rtsptoweb[316]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 19:18:00 archangel rtsptoweb[316]: goroutine 12 [running]:
Dec 04 19:18:00 archangel rtsptoweb[316]: main.(*StorageST).StreamChannelCastProxy(0xc00042a000, {0xc0003823c0, 0x24}, {0x11dfd28, 0x1}, 0xc00d3f9098)
Dec 04 19:18:00 archangel rtsptoweb[316]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 19:18:00 archangel rtsptoweb[316]: main.StreamServerRunStream({0xc0003823c0, 0x24}, {0x11dfd28, 0x1}, 0xc0003a6790)
Dec 04 19:18:00 archangel rtsptoweb[316]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 19:18:00 archangel rtsptoweb[316]: main.StreamServerRunStreamDo({0xc0003823c0, 0x24}, {0x11dfd28, 0x1})
Dec 04 19:18:00 archangel rtsptoweb[316]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 19:18:00 archangel rtsptoweb[316]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 19:18:00 archangel rtsptoweb[316]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 19:18:01 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 19:18:01 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 19:18:01 archangel systemd[1]: rtsptoweb.service: Consumed 17min 29.779s CPU time.
Dec 04 19:18:11 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 1.
Dec 04 19:18:24 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 19:18:24 archangel systemd[1]: rtsptoweb.service: Consumed 17min 29.779s CPU time.
Dec 04 19:18:24 archangel systemd[1]: Started RTSPtoWeb server.

Dec 04 19:35:42 archangel rtsptoweb[1875]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 19:35:42 archangel rtsptoweb[1875]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 19:35:42 archangel rtsptoweb[1875]: goroutine 42 [running]:
Dec 04 19:35:42 archangel rtsptoweb[1875]: main.(*StorageST).StreamChannelCastProxy(0xc0002fc5a0, {0xc000363020, 0x24}, {0x11dfd20, 0x1}, 0xc0022ffcb0)
Dec 04 19:35:42 archangel rtsptoweb[1875]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 19:35:42 archangel rtsptoweb[1875]: main.StreamServerRunStream({0xc000363020, 0x24}, {0x11dfd20, 0x1}, 0xc0004ea210)
Dec 04 19:35:42 archangel rtsptoweb[1875]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 19:35:42 archangel rtsptoweb[1875]: main.StreamServerRunStreamDo({0xc000363020, 0x24}, {0x11dfd20, 0x1})
Dec 04 19:35:42 archangel rtsptoweb[1875]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 19:35:42 archangel rtsptoweb[1875]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 19:35:42 archangel rtsptoweb[1875]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 19:35:42 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 19:35:42 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 19:35:42 archangel systemd[1]: rtsptoweb.service: Consumed 5min 4.296s CPU time.
Dec 04 19:35:53 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 2.
Dec 04 19:36:13 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 19:36:13 archangel systemd[1]: rtsptoweb.service: Consumed 5min 4.296s CPU time.
Dec 04 19:36:13 archangel systemd[1]: Started RTSPtoWeb server.

Dec 04 20:35:23 archangel rtsptoweb[2197]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 20:35:23 archangel rtsptoweb[2197]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 20:35:23 archangel rtsptoweb[2197]: goroutine 47 [running]:
Dec 04 20:35:23 archangel rtsptoweb[2197]: main.(*StorageST).StreamChannelCastProxy(0xc0003485a0, {0xc0003acf30, 0x24}, {0x11dfd28, 0x1}, 0xc0026621f8)
Dec 04 20:35:23 archangel rtsptoweb[2197]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 20:35:23 archangel rtsptoweb[2197]: main.StreamServerRunStream({0xc0003acf30, 0x24}, {0x11dfd28, 0x1}, 0xc000437b80)
Dec 04 20:35:23 archangel rtsptoweb[2197]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 20:35:23 archangel rtsptoweb[2197]: main.StreamServerRunStreamDo({0xc0003acf30, 0x24}, {0x11dfd28, 0x1})
Dec 04 20:35:23 archangel rtsptoweb[2197]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 20:35:23 archangel rtsptoweb[2197]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 20:35:23 archangel rtsptoweb[2197]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 20:35:23 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 20:35:23 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 20:35:23 archangel systemd[1]: rtsptoweb.service: Consumed 16min 58.988s CPU time.
Dec 04 20:35:33 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 3.
Dec 04 20:35:54 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 20:35:54 archangel systemd[1]: rtsptoweb.service: Consumed 16min 58.988s CPU time.
Dec 04 20:35:54 archangel systemd[1]: Started RTSPtoWeb server.

Dec 04 21:10:34 archangel rtsptoweb[3541]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 21:10:34 archangel rtsptoweb[3541]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 21:10:34 archangel rtsptoweb[3541]: goroutine 30 [running]:
Dec 04 21:10:34 archangel rtsptoweb[3541]: main.(*StorageST).StreamChannelCastProxy(0xc0003065a0, {0xc0003330e0, 0x24}, {0x11dfd20, 0x1}, 0xc011c7e8d0)
Dec 04 21:10:34 archangel rtsptoweb[3541]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 21:10:34 archangel rtsptoweb[3541]: main.StreamServerRunStream({0xc0003330e0, 0x24}, {0x11dfd20, 0x1}, 0xc0003b8000)
Dec 04 21:10:34 archangel rtsptoweb[3541]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 21:10:34 archangel rtsptoweb[3541]: main.StreamServerRunStreamDo({0xc0003330e0, 0x24}, {0x11dfd20, 0x1})
Dec 04 21:10:34 archangel rtsptoweb[3541]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 21:10:34 archangel rtsptoweb[3541]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 21:10:34 archangel rtsptoweb[3541]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 21:10:34 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 21:10:34 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 21:10:34 archangel systemd[1]: rtsptoweb.service: Consumed 10min 12.948s CPU time.
Dec 04 21:10:45 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 4.
Dec 04 21:11:05 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 21:11:05 archangel systemd[1]: rtsptoweb.service: Consumed 10min 12.948s CPU time.
Dec 04 21:11:06 archangel systemd[1]: Started RTSPtoWeb server.

Dec 04 21:37:55 archangel rtsptoweb[4008]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 21:37:55 archangel rtsptoweb[4008]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 21:37:55 archangel rtsptoweb[4008]: goroutine 40 [running]:
Dec 04 21:37:55 archangel rtsptoweb[4008]: main.(*StorageST).StreamChannelCastProxy(0xc0002fa5a0, {0xc000365020, 0x24}, {0x11dfd20, 0x1}, 0xc00fcde1f8)
Dec 04 21:37:55 archangel rtsptoweb[4008]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 21:37:55 archangel rtsptoweb[4008]: main.StreamServerRunStream({0xc000365020, 0x24}, {0x11dfd20, 0x1}, 0xc0004fe630)
Dec 04 21:37:55 archangel rtsptoweb[4008]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 21:37:55 archangel rtsptoweb[4008]: main.StreamServerRunStreamDo({0xc000365020, 0x24}, {0x11dfd20, 0x1})
Dec 04 21:37:55 archangel rtsptoweb[4008]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 21:37:55 archangel rtsptoweb[4008]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 21:37:55 archangel rtsptoweb[4008]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 21:37:55 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 21:37:55 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 21:37:55 archangel systemd[1]: rtsptoweb.service: Consumed 7min 49.036s CPU time.
Dec 04 21:38:05 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 5.
Dec 04 21:38:25 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 21:38:25 archangel systemd[1]: rtsptoweb.service: Consumed 7min 49.036s CPU time.
Dec 04 21:38:25 archangel systemd[1]: Started RTSPtoWeb server.

Dec 04 22:06:59 archangel rtsptoweb[4861]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 04 22:06:59 archangel rtsptoweb[4861]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xae1a47]
Dec 04 22:06:59 archangel rtsptoweb[4861]: goroutine 38 [running]:
Dec 04 22:06:59 archangel rtsptoweb[4861]: main.(*StorageST).StreamChannelCastProxy(0xc0003085a0, {0xc0003290e0, 0x24}, {0x11dfd20, 0x1}, 0xc012d30f18)
Dec 04 22:06:59 archangel rtsptoweb[4861]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:221 +0x307
Dec 04 22:06:59 archangel rtsptoweb[4861]: main.StreamServerRunStream({0xc0003290e0, 0x24}, {0x11dfd20, 0x1}, 0xc0003b5ce0)
Dec 04 22:06:59 archangel rtsptoweb[4861]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:139 +0x1079
Dec 04 22:06:59 archangel rtsptoweb[4861]: main.StreamServerRunStreamDo({0xc0003290e0, 0x24}, {0x11dfd20, 0x1})
Dec 04 22:06:59 archangel rtsptoweb[4861]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/streamCore.go:47 +0x465
Dec 04 22:06:59 archangel rtsptoweb[4861]: created by main.(*StorageST).StreamChannelRunAll
Dec 04 22:06:59 archangel rtsptoweb[4861]:         /home/mad/.cache/yay/rtsptoweb/src/RTSPtoWeb-2.4.0/storageStreamChannel.go:42 +0x265
Dec 04 22:06:59 archangel systemd[1]: rtsptoweb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 04 22:06:59 archangel systemd[1]: rtsptoweb.service: Failed with result 'exit-code'.
Dec 04 22:06:59 archangel systemd[1]: rtsptoweb.service: Consumed 8min 11.049s CPU time.
Dec 04 22:07:09 archangel systemd[1]: rtsptoweb.service: Scheduled restart job, restart counter is at 6.
Dec 04 22:07:29 archangel systemd[1]: Stopped RTSPtoWeb server.
Dec 04 22:07:29 archangel systemd[1]: rtsptoweb.service: Consumed 8min 11.049s CPU time.
Dec 04 22:07:29 archangel systemd[1]: Started RTSPtoWeb server.
```

**Comment by deepch** [comment]
show you config

**Comment by seededplyr** [comment]
```
{
  "channel_defaults": {},
  "server": {
    "debug": false,
    "http_debug": false,
    "http_demo": true,
    "http_dir": "web",
    "http_login": "demo",
    "http_password": "demo",
    "http_port": ":9000",
    "https": false,
    "https_auto_tls": false,
    "https_auto_tls_name": "",
    "https_cert": "server.crt",
    "https_key": "server.key",
    "https_port": ":443",
    "ice_credential": "",
    "ice_servers": [
      "stun:stun.l.google.com:19302"
    ],
    "ice_username": "",
    "log_level": "error",
    "rtsp_port": ":5541",
    "token": {
      "backend": "",
      "enable": false
    },
    "webrtc_port_max": 0,
    "webrtc_port_min": 0
  },
  "streams": {
    "0999b447-c370-4de4-b1f7-6cd728d5208a": {
      "channels": {
        "0": {
          "url": "rtsp://192.168.1.19:554/ch0_0.h264"
        },
        "1": {
          "url": "rtsp://192.168.1.19:554/ch0_1.h264"
        }
      },
      "name": "Indoor1"
    },
    "167e4860-a7fb-44ba-a2b7-9e9d7fa2ba21": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.25:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.25:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "West Lawn"
    },
    "318e338e-7b8b-420b-8b1e-52728d46f400": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.21:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.21:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "North Porch"
    },
    "362f6461-58d1-4411-85ee-49cfebf590d5": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.23:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.23:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "East Lawn"
    },
    "4615d292-f493-4cfc-bd70-0d42596974e9": {
      "channels": {
        "0": {
          "url": "rtsp://192.168.1.20:554/ch0_0.h264"
        },
        "1": {
          "url": "rtsp://192.168.1.20:554/ch0_1.h264"
        }
      },
      "name": "Indoor2"
    },
    "b02650bf-ce87-4a92-9cb1-f90913725ddd": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.22:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.22:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "West Porch"
    },
    "b1ad1b5e-eda5-4eba-98e4-5cef0cea6e1a": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.24:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.24:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "South Kitchen"
    },
    "c2058cfa-1dc0-4988-8c49-8410aa2a50c5": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.27:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.27:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "Porch"
    },
    "da44892a-fb2c-4f7f-a29e-5d756b2bf86a": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.28:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.28:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "West Lawn Rear"
    },
    "e27ebf89-b3b2-4fec-96ff-150772c537b4": {
      "channels": {
        "0": {
          "url": "rtsp://admin:nimda@192.168.1.26:554/cam/realmonitor?channel=1\u0026amp;subtype=0"
        },
        "1": {
          "url": "rtsp://admin:nimda@192.168.1.26:554/cam/realmonitor?channel=1\u0026amp;subtype=1"
        }
      },
      "name": "East Lawn Rear"
    }
  }
}

```

**Comment by seededplyr** [comment]
> 
thank you very much btw, your incredible work on this opensource project is immense and appreciated.

**Comment by deepch** [comment]
check now

**Comment by seededplyr** [comment]
> 

do you mean I should check something? or that you are checking something? sorry I don't understand.

**Comment by deepch** [comment]
update source from my git and make new binary

**Comment by seededplyr** [comment]
> update source from my git and make new binary

ok will do, thank you, will update once ive done that

**Comment by seededplyr** [comment]
Ok, new source built and now running, will keep you posted

**Comment by seededplyr** [comment]
FYI @deepch I should have mentioned that I was running release 2.4.0 when those errors were occurring. Also, its been running now for half hour without any error. Will keep you posted.

**Comment by deepch** [comment]
@allenporter

**Comment by seededplyr** [comment]
@deepch 1hr 30mins without errors, thank you very much, I will close this issue now.
