### ISSUE TITLE
Play Huawei SDC video stream code through webrtc and exit

### ISSUE THREAD

**Issue by nightzjp** [deepch/RTSPtoWeb#63]
2021/09/06 11:12:03 [Unsupported NAL Type 6]
panic: runtime error: index out of range [0] with length 0 --> log

goroutine 89 [running]:
github.com/deepch/vdk/codec/h264parser.CodecData.SPS(...)
        /Users/mac/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210523103705-5b25bda1a000/codec/h264parser/parser.go:666
github.com/deepch/vdk/format/webrtcv3.(*Muxer).WritePacket(0xc0000fe0e0, 0x1, 0xf4240, 0x107b3806edc0, 0x0, 0xc00079c000, 0x471b4, 0x48000, 0x0, 0x0)
        /Users/mac/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210523103705-5b25bda1a000/format/webrtcv3/adapter.go:216 +0x8ac
main.HTTPAPIServerStreamWebRTC.func1(0xc00014e100, 0xc0002feaf0, 0xc0000fe0e0)
        /Users/mac/Project/goland/RTSPtoWeb/apiHTTPWebRTC.go:81 +0x657
created by main.HTTPAPIServerStreamWebRTC
        /Users/mac/Project/goland/RTSPtoWeb/apiHTTPWebRTC.go:53 +0xe6e
exit status 2

**Comment by nightzjp** [comment]
MSE and HLS can be played, and the webrtc code will be interrupted

**Comment by deepch** [comment]
make access to your camera via the Internet.

**Comment by nightzjp** [comment]
I have no problem logging in to the camera directly through the browser

**Comment by nightzjp** [comment]
My camera is currently accessible only on the LAN

**Comment by deepch** [comment]
I want to make rtsp access for me. so that I can check.

**Comment by nightzjp** [comment]
Wait a minute. I'll configure the camera's Internet address

**Comment by nightzjp** [comment]
Sorry, our camera can't be accessed through the Internet; Can I debug on my computer through remote software? thank you

**Comment by nightzjp** [comment]
> I want to make rtsp access for me. so that I can check.

Are you free now? I'll send you the RTSP address

**Comment by deepch** [comment]
worked now?

**Comment by nightzjp** [comment]
> ?

There is something wrong with the network today. We can only test it tomorrow. sorry. No problem with the test. I'll reply

**Comment by nightzjp** [comment]
Now the process has not exited, but the video still cannot be played (it can be played normally for a while, and it can not be played again for a while)


在 2021年9月7日 17:42，Andrey ***@***.***> 写道：


worked now?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deepch** [comment]
show you config

**Comment by nightzjp** [comment]
I tested several times on my local computer and LAN server:
1. The top of the local computer will have a blue screen
2. The server cannot play directly on the black screen

**Comment by nightzjp** [comment]
Hello, I just tested it. When the code runs on an arm64 server, the Huawei camera cannot play the video stream. Other devices play normally;
When I run the code in x86 architecture. All equipment is working properly.
thank you

**Comment by deepch** [comment]
run mse and webrtc tests in different browsers with option  "on_demand": false,

**Comment by nightzjp** [comment]
I tested Google, Firefox, safra, QQ and 360 browsers. They can all be played. Only the top of the webrtc stream I sent you by email will flash frequently. I changed the camera of the same model and it won't flash···

**Comment by deepch** [comment]
share you rtsp stream I can check it.
