### ISSUE TITLE
Crash when editing stream from persistent to on-demand

### ISSUE THREAD

**Issue by Bhlowe** [deepch/RTSPtoWeb#72]
[ This is such a cool project!!!  Works really well. Thank you. ]

First bug report:

I edited an rtsp stream from persistent to on-demand.. 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xbe18a9]

goroutine 7447 [running]:
main.(*MuxerHLS).SetFPS(...)
        /data/dev/RTSPtoWeb/hlsMuxer.go:43
main.(*StorageST).HlsMuxerSetFPS(0xc00035a0e0, 0xc00003ec0d, 0x24, 0x1499730, 0x1, 0x19)
        /data/dev/RTSPtoWeb/storageStreamChannel.go:353 +0x1e9
main.StreamServerRunStream(0xc00003ec0d, 0x24, 0x1499730, 0x1, 0xc000302420, 0x0, 0x0, 0x0)
        /data/dev/RTSPtoWeb/streamCore.go:172 +0xd18
main.StreamServerRunStreamDo(0xc00003ec0d, 0x24, 0x1499730, 0x1)
        /data/dev/RTSPtoWeb/streamCore.go:43 +0x4db
created by main.(*StorageST).StreamEdit
        /data/dev/RTSPtoWeb/storageStream.go:65 +0x636
exit status 2

**Comment by realjax** [comment]
+1. Also I have noticed that 

- when it does not cause a crash, changing the state an rtsp stream from persistent to on-demand is not saved in config.json. 

- if the state is manually set to on-demand: true in the config.json,  this setting is changed when the program runs for a while,  to persistent again. 
 
very strange behaviour.
